version: 2
project_name: frink

before:
  hooks:
  - go mod tidy
  - go mod download

release:
  prerelease: auto

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  ldflags:
  - -s -w -X github.com/uitml/frink/cmd.version={{ .Version }} -X github.com/uitml/frink/cmd.commit={{ .ShortCommit }}  -X github.com/uitml/frink/cmd.date={{ .Date }}

archives:
- format: binary
  name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
  replacements:
    darwin: macos

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ replace .Tag "v" "" }}-{{ .ShortCommit }}'

changelog:
  skip: true
