project_name: frink

before:
  hooks:
  - go mod tidy
  - go mod download

release:
  prerelease: auto

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  goarch:
  - amd64

archives:
- format: binary
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: macOS
    linux: Linux
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ replace .Tag "v" "" }}-{{ .ShortCommit }}'

changelog:
  skip: true
