name: ci

on:
  push:
    branches:
    - main
    paths-ignore:
    - docs/**
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24
        cache: true

    - name: Download Go modules
      run: go mod download

    - name: Run tests
      run: go test -race -covermode atomic ./...
